---
kind: pipeline
type: docker
name: linux-amd64

platform:
  arch: amd64
  os: linux

steps:
- name: test
  image: dazz111/ubuntu-sdk:build
  commands:
  - docker login -u $USER_NAME -p $PASSWORD
  - bash build.sh
